# Generated by Django 5.1.1 on 2024-10-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charackterstick",
            fields=[
                (
                    "id_charackterstick",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("charackterstick1", models.CharField(max_length=255)),
                ("charackterstick2", models.CharField(max_length=255)),
                ("charackterstick3", models.CharField(max_length=255)),
                ("charackterstick4", models.CharField(max_length=255)),
                ("charackterstick5", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id_category", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "charackterstick",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.charackterstick",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id_product", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="products/")),
                ("rating1", models.IntegerField(default=0)),
                ("rating2", models.IntegerField(default=0)),
                ("rating3", models.IntegerField(default=0)),
                ("rating4", models.IntegerField(default=0)),
                ("rating5", models.IntegerField(default=0)),
                ("ratingall", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.category",
                    ),
                ),
            ],
        ),
    ]
