# Generated by Django 5.1.1 on 2024-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_charackterstickservice_product_textdes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratingbef1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratingbef2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratingbef3",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratingbef4",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratingbef5",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ratingbef1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ratingbef2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ratingbef3",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ratingbef4",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="service",
            name="ratingbef5",
            field=models.IntegerField(default=0),
        ),
    ]
