# Generated by Django 5.1.1 on 2024-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_product_counter_product_ratingbef1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charackterstickservice",
            name="name",
            field=models.CharField(
                default="Отсутствует название групп характеристик", max_length=255
            ),
        ),
    ]
