# Generated by Django 5.1.1 on 2024-10-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_charackterstickservice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="charackterstick",
            name="name",
            field=models.CharField(
                default="Отсутствует название групп характеристик", max_length=255
            ),
        ),
    ]
